#!/usr/bin/env php
<?php
/**
 * -----------------------------------------------------------------------------
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 * -----------------------------------------------------------------------------
 */
require(__DIR__ . '/env.php');
require(__DIR__ . '/src/vendor/autoload.php');
require(__DIR__ . '/src/vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/src/common/config/bootstrap.php');
require(__DIR__ . '/src/console/config/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/src/common/config/main.php'),
    require(__DIR__ . '/src/console/config/main.php')
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
