<?php
/**
 * Created by PhpStorm.
 * @author: Fred <fred@btimillman.com>
 * Date & Time: 2017-04-08 1:00 PM
 */
return [
    [
        'class' => \yii\rest\UrlRule::class,
        'pluralize' => false,
        'controller' => [
            'user' => 'v1/user',
            'bank' => 'v1/bank',
            'bank-branch' => 'v1/bank-branch',
            'organization-branch' => 'v1/organization-branch',
            'salutation' => 'v1/salutation',
            'country' => 'v1/country',
            'identity-type' => 'v1/identity-type',
            'gender' => 'v1/gender',
            'marital-status' => 'v1/marital-status',
            'client-group' => 'v1/client-group',
            'postal-code' => 'v1/postal-code',
            'religion' => 'v1/religion',
            'education-level' => 'v1/education-level',
            'client-account-types' => 'v1/client-account-types',
            'client-status' => 'v1/client-status',
            'client-residence-types' => 'v1/client-residence-types',
            'person-relationship-type' => 'v1/person-relationship-type',
            'document-type' => 'v1/document-type',
            'employer'=>'v1/employer',
            'employment-term'=>'v1/employment-term',
            'currency' => 'v1/currency',
            'months-options' => 'v1/month-options',
            'years-options' => 'v1/year-options',
        ],
        'tokens' => [
            '{id}' => '<id:\\w+>',
            '{code}' => '<code:\\w+>',
        ],
        'extraPatterns' => [
            'GET index' => 'index',
            'GET view' => 'view',
            'OPTIONS <action>' => 'options',
        ],
    ],

    [
        'class' => \yii\rest\UrlRule::class,
        'pluralize' => false,
        'controller' => [
            'users' => 'v1/user',
            'settings' => 'v1/settings',
        ],
        'tokens' => [
            '{id}' => '<id:\\w+>',
            '{code}' => '<code:\\w+>',
        ],
        'extraPatterns' => [
        ]
    ],

    [
        'class' => \yii\rest\UrlRule::class,
        'pluralize' => false,
        'controller' => [
            'auth' => 'v1/auth',
        ],
        'extraPatterns' => [
            'POST login' => 'login',
            //'POST change-password' => 'change-password',
            //'POST reset-password/begin' => 'begin-reset-password',
            //'POST reset-password/finish' => 'complete-reset-password',
            //'POST reset-password/finish/{token}' => 'complete-reset-password',
            'GET activation-code' => 'activation-code',
            'POST new-password' => 'new-password',
            'OPTIONS <action>' => 'options',
        ],
    ],
    [
        'class' => \yii\rest\UrlRule::class,
        'pluralize' => false,
        'controller' => [
            'client' => 'v1/client',
            'client-kin' => 'v1/client-kin',
            'client-bank' => 'v1/client-bank',
            'client-document' => 'v1/client-document',
            'client-kin-document' => 'v1/client-kin-document',
            'client-residence' => 'v1/client-residence',
            'client-work-info' => 'v1/client-work-information',
        ],
        'tokens' => [
            '{id}' => '<id:\\w+>',
        ],
        'extraPatterns' => [
            'GET index' => 'index',
            'GET view' => 'view',
            'GET view/kin' => 'view-kin',
            'POST create/basic' => 'create-basic',
            'POST create/bank-accounts' => 'create-bank-accounts',
            'POST create/kin' => 'create-kin',
            'POST create/work-info' => 'create-work-information',
            'POST create/residence-info' => 'create-residence-information',
            'POST create/document' => 'create-document',
            'POST create/kin-document' => 'create-kin-document',
            'PUT update/basic' => 'update-basic',
            'PUT update/bank-account' => 'update-bank-account',
            'PUT update/kin' => 'update-kin',
            'PUT update/work-info' => 'update-work-information',
            'PUT update/residence-info' => 'update-residence-information',
            'PUT update/document' => 'update-document',
            'PUT update/kin-document' => 'update-kin-document',
            //'GET kins' => 'client-kin/index',
            'OPTIONS <action>' => 'options',
        ],
    ],
    // saving sub-module
    [
        'class' => \yii\rest\UrlRule::class,
        'pluralize' => false,
        'controller' => [
            'saving-summary' => 'v1/saving/dashboard',
            'saving-account' => 'v1/saving/account',
            'saving-account-kin' => 'v1/saving/account-kin',
            'account-statement' => 'v1/saving/account-statement',
            'bulk-withdrawal' => 'v1/saving/bulk-withdrawal',
            'saving-transaction' => 'v1/saving/transaction',
            'payment-deposit' => 'v1/saving/deposit',
            'transaction-reversal' => 'v1/saving/reversal',
            'saving-account-withdrawal' => 'v1/saving/account-withdrawal',
            'saving-dividend-payment' => 'v1/saving/dividend-payment',
            'saving-dividend-payment-prorate' => 'v1/saving/dividend-payment-prorate',
            'saving-dividend-payment-schedule' => 'v1/saving/dividend-payment-schedule',
            'saving-account-document' => 'v1/saving/account-document',
            'saving-internal-transfer' => 'v1/saving/internal-transfer',
            'automated-internal-transfer' => 'v1/saving/automated-transfer',
            'transaction-status' => 'v1/saving/transaction-status',
            'transaction-type' => 'v1/saving/transaction-type',
            'entry-types' => 'v1/saving/entry-types',
            'interest-computation-methods' => 'v1/saving/interest-computation-methods',
            'list-options' => 'v1/saving/list-options',
            'fixed-deposit-rollover-methods' => 'v1/saving/fixed-deposit-rollover-methods',
            'payment-modes' => 'v1/saving/payment-modes',
            'payroll-months' => 'v1/saving/payroll-months',
            'payroll-years' => 'v1/saving/payroll-years',
            'withdraw-notice' => 'v1/saving/withdraw-notice',
        ],
        'tokens' => [
            '{id}' => '<id:\\w+>',
            '{code}' => '<code:\\w+>',
        ],
        'extraPatterns' => [
            'GET index' => 'index',
            'GET view' => 'view',
            'POST create' => 'create',
            'POST,PUT update' => 'update',
            'GET download-receipt' => 'download-receipt',
            'POST update-doc' => 'update-document',
            'GET receipt' => 'receipt',
            'POST post' => 'post-schedule',
            'OPTIONS <action>' => 'options',
        ],
    ],
    // loan sub-module
    [
        'class' => \yii\rest\UrlRule::class,
        'pluralize' => false,
        'controller' => [
            'loan' => 'v1/loan/loan',
            'loan-appraisal' => 'v1/loan/loan-appraisal',
            'loan-guarantor' => 'v1/loan/guarantor',
            'loan-disbursement' => 'v1/loan/disbursement',
            'loan-fees' => 'v1/loan/loan-fees',
            'loan-document' => 'v1/loan/loan-document',
            'loan-collateral' => 'v1/loan/loan-collateral',
            'loan-repayment-schedule' => 'v1/loan/repayment-schedule',
            'loan-rescheduling' => 'v1/loan/loan-rescheduling',
            'loan-repayment-transaction' => 'v1/loan/repayment-transaction',
            'loan-guarantor-release-history' => 'v1/loan/guarantor-release-history',
            'loan-summary-report' => 'v1/loan/summary-report',
            'loan-calculation-methods' => 'v1/loan/calculation-methods',
            'loan-recovery-methods' => 'v1/loan/recovery-methods',
            'loan-purpose-reference' => 'v1/loan/purpose-reference',
            'loan-period-measure-options' => 'v1/loan/period-measure-options',
            'guarantor-document' => 'v1/loan/guarantor-document',
            'loan-transaction-types' => 'v1/loan/transaction-types',
        ],
        'tokens' => [
            '{id}' => '<id:\\w+>',
            '{code}' => '<code:\\w+>',
        ],
        'extraPatterns' => [
            'GET index' => 'index',
            'GET view' => 'view',
            'POST create' => 'create',
            'POST,PUT update' => 'update',
            'POST get-calculated-fields' => 'get-calculated-fields',
            'POST cancel' => 'cancel',
            'POST approve' => 'approve',
            'POST recover' => 'recover',
            'POST write-off' => 'write-off',
            'POST reverse-write-off' => 'reverse-write-off',
            'POST transfer-to-guarantor' => 'transfer-to-guarantor',
            'POST get-repayment-schedule' => 'get-repayment-schedule',
            'POST preview-schedule' => 'preview-schedule',
            'POST remove' => 'remove',
            'POST create-internal' => 'create-internal',
            'POST create-external' => 'create-external',
            'POST transfer' => 'transfer', // loan-rescheduling Transfer Principal Balance
            'POST get-refinancing-fees' => 'get-refinancing-fees',
            'POST update-doc' => 'update-doc',
            'GET download' => 'download',
            'GET voucher' => 'voucher',
            'GET download-voucher' => 'download-voucher',
            'OPTIONS <action>' => 'options',
        ],
    ],
    // product sub-module
    [
        'class' => \yii\rest\UrlRule::class,
        'pluralize' => false,
        'controller' => [
            'product' => 'v1/product/product',
            'loan-products-list' => 'v1/product/loan-products-list',
            'saving-products-list' => 'v1/product/saving-products-list',
        ],
        'tokens' => [
            '{id}' => '<id:\\w+>',
            '{code}' => '<code:\\w+>',
        ],
        'extraPatterns' => [
            'GET index' => 'index',
            'GET view' => 'view',
            'POST create' => 'create',
            'PUT update' => 'update',
            'OPTIONS <action>' => 'options',
        ],
    ],
];